seguidor_waypoints:
  ros__parameters:
    use_sim_time: true

    control_rate: 50.0
    odom_topic: /odom
    cmd_vel_topic: /cmd_vel

    controlador: continuo

    registro_csv: ''

    repetir: false              

    waypoints: [p1, p2, p3, p4]

    p1: {x: 1.0, y: 0.0, theta: 1.5708}    # 90°
    p2: {x: 1.0, y: 1.0, theta: 3.1416}    # 180°
    p3: {x: 0.0, y: 1.0, theta: -1.5708}   # -90°
    p4: {x: 0.0, y: 0.0, theta: 0.0}       # volta à origem

    
    continuo:
      pid_x:                     # e_x^b  
        kp: 1.2
        ki: 0.0
        kd: 0.0
      pid_y:                     # e_y^b  
        kp: 8.0
        ki: 0.0
        kd: 0.0
      pid_theta:                 # e_theta  (alinhamento final)
        kp: 1.5
        ki: 0.0
        kd: 0.0
      max_linear_vel: 0.3        
      max_angular_vel: 1.0       
      position_tolerance: 0.03   
      yaw_tolerance: 0.05        
      alignment_hysteresis: 2.0  

    manobras:
      k_linear: 0.5
      k_angular: 1.5
      v_max: 0.3                
      w_max: 1.0                 
      tol_distancia: 0.02        
      tol_angulo: 0.02           
